export HDF5_PLUGIN_PATH=$HDF5_PLUGIN_PATH:$PWD
export FILTER_LIB_PATH=$HDF5_PLUGIN_PATH:$FILTER_LIB_PATH
export LD_LIBRARY_PATH=$HDF5_PLUGIN_PATH:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$HDF5_PLUGIN_PATH:$DYLD_LIBRARY_PATH

