export HDF5_PLUGIN_PATH=$HDF5_PLUGIN_PATH:$PWD
##export HDF5_HOME=/Users/dbin/work/soft/hdf5-1.10.7/build
export FILTER_LIB_PATH=$HDF5_PLUGIN_PATH
export LD_LIBRARY_PATH=$HDF5_PLUGIN_PATH
export DYLD_LIBRARY_PATH=$HDF5_PLUGIN_PATH

